library/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.views import LogoutView



app_name = 'library'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('info-register/', InformationView.as_view(), name='info-register'),


    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='library:login'), name='logout'),

    path('books/', BookView.as_view(), name='book-list'),
    path('book/create/', BookCreate.as_view(), name='book-create'),
    path('book/<slug:pk>/', BookDetail.as_view(), name= 'book'),
    path('book/<slug:pk>/update/', BookUpdate.as_view(), name='book-update'),
    path('book/<slug:pk>/delete/', BookDelete.as_view(), name='book-delete'),



    path('members/', MemberView.as_view(), name='member-list'),
    path('member/create/', MemberCreate.as_view(), name='member-create'),
    path('member/<slug:pk>/', MemberDetail.as_view(), name='member-detail'),
    path('member/<slug:pk>/update/', MemberUpdate.as_view(), name='member-update'),
    path('member/<slug:pk>/delete/', MemberDelete.as_view(), name='member-delete'),

    path('users/', UsersView.as_view(), name='users-list'),
    path('users/create/', UsersCreate.as_view(), name='users-create'),
    path('user/<slug:pk>/', UsersDetail.as_view(), name='users-detail'),


    path('borrowers/', BorrowerView.as_view(), name='borrower-list'),
    path('borrower/create/', BorrowerCreate.as_view(), name='borrower-create'),
    path('borrower/<slug:pk>/', BorrowerDetail.as_view(), name= 'borrower'),
    path('borrower/<slug:pk>/update/', BorrowerUpdate.as_view(), name='borrower-update'),
    path('borrower/<slug:pk>/delete/', BorrowerDelete.as_view(), name='borrower-delete'),



]

library_config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from .models import Account


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Add a valid email address.')

    class Meta:
        model = Account
        fields = ('email', 'name', 'username','enrollment_no', 'password1', 'password2','pic' )


class AccountAuthenticationForm(forms.ModelForm):

	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	class Meta:
		model = Account
		fields = ('email', 'password')

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError("Invalid login")


class AccountUpdateForm(forms.ModelForm):

	class Meta:
		model = Account
		fields = ('email','name' ,'username', 'pic' )

	def clean_email(self):
		email = self.cleaned_data['email']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
		except Account.DoesNotExist:
			return email
		raise forms.ValidationError('Email "%s" is already in use.' % account)

	def clean_username(self):
		username = self.cleaned_data['username']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
		except Account.DoesNotExist:
			return username
		raise forms.ValidationError('Username "%s" is already in use.' % username)

library/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView, FormView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.urls import reverse_lazy
from .forms import *
from django.http import request
from datetime import datetime, timedelta
from django.contrib import messages


class UserAccessMixin(PermissionRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        if not self.has_permission():
            return redirect('library:home')
        return super(UserAccessMixin, self).dispatch(request, *args, **kwargs)




class UserLoginView(LoginView):
    template_name='library/login.html'
    fields='__all__'
    redirect_authenticated_user=True

    def get_success_url(self):
        return reverse_lazy('library:home')

class InformationView(CreateView):
    template_name='library/information_form.html'
    model=InformationForm
    context_object_name="account_register"
    fields=['email', 'name', 'username', 'member']
    success_url=reverse_lazy('library:login')

    def form_valid(self, form):
        form.instance.user=self.request.user
        return super(InformationView, self).form_valid(form)


class HomeView(LoginRequiredMixin, TemplateView):
    template_name='library/main.html'
    

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['accounts']=Account.objects.all()
        context['books'] = Book.objects.all()
        search_input=self.request.GET.get('search-area') or ''
        if search_input:
            context['books']=context['books'].filter(
                title__startswith=search_input)

        context['search_input']=search_input
        return context

# Book views classes

class BookView(LoginRequiredMixin, ListView):
    model=Book
    context_object_name='books'

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['books']=context['books']

        search_input=self.request.GET.get('search-area') or ''
        if search_input:
            context['books']=context['books'].filter(
                title__startswith=search_input)

        context['search_input']=search_input

        return context



class BookCreate(LoginRequiredMixin, UserAccessMixin, CreateView):
    model=Book
    permission_required= 'books.add_books'
    fields='__all__'
    success_url=reverse_lazy('library:book-list')


    def form_valid(self, form):
        form.instance.user=self.request.user
        return super(BookCreate, self).form_valid(form)



class BookDetail(LoginRequiredMixin, DetailView):
    model=Book
    context_object_name='book'
    template_name='library/book.html'


    


class BookUpdate(LoginRequiredMixin,UserAccessMixin,  UpdateView):
    model=Book
    permission_required = 'books.change_books'
    fields='__all__'
    success_url=reverse_lazy('library:book-list')


class BookDelete(LoginRequiredMixin,UserAccessMixin,  DeleteView):
    model=Book
    permission_required = 'books.delete_book'
    context_object_name='book'
    fields='__all__'
    success_url=reverse_lazy('library:book-list')


# Member views classes
class MemberView(LoginRequiredMixin, UserAccessMixin, ListView):
    model=Account
    context_object_name='members'
    permission_required = 'members.view_members'
    template_name='library/member_list.html'

    def get_context_data(self,  *args,**kwargs):
        context=super().get_context_data(**kwargs)
        context['members']=context['members'].exclude(is_admin=True)
        search_input=self.request.GET.get('search-area') or ''
        if search_input:
            context['members']=context['members'].filter(name__startswith=search_input)

        context['search_input']=search_input

        return context


class MemberDetail(LoginRequiredMixin, DetailView):
    model=Account
    context_object_name='member'
    template_name='library/member.html'




class MemberCreate(UserAccessMixin, CreateView):
    template_name = 'library/register.html'
    form_class = RegistrationForm
    permission_required = 'users.add_users'
    success_url = reverse_lazy('library:member-list')

    def form_valid(self, form):
        form.instance.user=self.request.user
        return super(MemberCreate, self).form_valid(form)


class MemberUpdate(LoginRequiredMixin, UpdateView):
    form_class = AccountUpdateForm
    template_name = 'library/member_update.html'
    model = Account
    success_url=reverse_lazy('library:member-list')
    

    def form_valid(self, form):
        user = form.save()
        return super(MemberUpdate, self).form_valid(form)

class MemberDelete(LoginRequiredMixin,UserAccessMixin,  DeleteView):
    model=Account
    template_name = 'library/member_confirm_delete.html'
    permission_required = 'users.delete_users'
    context_object_name='member'
    fields='__all__'
    success_url=reverse_lazy('library:member-list')

# Users views classes
class UsersView(LoginRequiredMixin, UserAccessMixin, ListView):
    model=Account
    context_object_name='users'
    permission_required = 'users.view_users'
    template_name='library/users_list.html'

    def get_context_data(self,  *args,**kwargs):
        context=super().get_context_data(**kwargs)
        context['users']=context['users'].exclude(is_admin=False,is_staff=False,is_superuser=False, user_type=False)
        # .exclude(is_admin=True)
        search_input=self.request.GET.get('search-area') or ''
        if search_input:
            context['users']=context['users'].filter(name__startswith=search_input)

        context['search_input']=search_input

        return context

class UsersCreate(UserAccessMixin, CreateView):
    template_name = 'library/register.html'
    form_class = RegistrationForm
    permission_required = 'users.add_users'
    success_url = reverse_lazy('library:users-list')

    def form_valid(self, form):
        form.instance.user=self.request.user
        return super(UsersCreate, self).form_valid(form)

class UsersDetail(LoginRequiredMixin, DetailView):
    model=Account
    context_object_name='user'
    template_name='library/user.html'

# Borrower views classes
class BorrowerView(LoginRequiredMixin, ListView):
    model=Borrower
    context_object_name='borrowers'
    template_name = 'library/borrower_list.html'


    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        if self.request.user.is_admin or self.request.user.is_superuser:
            context['borrowers']=context['borrowers']
        else:
            context['borrowers']=context['borrowers'].filter(member = self.request.user.id)


        return context



class BorrowerCreate(LoginRequiredMixin, UserAccessMixin, CreateView):
    model=Borrower
    permission_required= 'borrowers.add_borrowers'
    fields='__all__'
    success_url=reverse_lazy('library:borrower-list')

   #remember to get the object using slug or 404 
    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        book = Book.objects.get(id=instance.book.id)
        member = Account.objects.get(id=instance.member.id)
        #get the book id from the form and check if the book is still available, then subtract.
        if book.available_copies > 0:
           book.available_copies -= 1
           book.save()
           instance.save()
           messages.success(self.request, "successful")
        messages.error(self.request, "Book not in stock")
        return redirect(reverse_lazy('library:borrower-list'))



class BorrowerDetail(LoginRequiredMixin,  DetailView):
    model=Borrower()
    context_object_name='borrower'
    template_name='library/borrower.html'
    


class BorrowerUpdate(LoginRequiredMixin,UserAccessMixin,  UpdateView):
    model=Borrower
    permission_required = 'borrowers.change_borrowers'
    fields='__all__'
    success_url=reverse_lazy('library:borrower-list')


class BorrowerDelete(LoginRequiredMixin,UserAccessMixin,  DeleteView):
    model=Borrower
    permission_required = 'borrowers.delete_borrowers'
    context_object_name='borrower'
    fields='__all__'
    success_url=reverse_lazy('library:borrower-list')


    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        book = Book.objects.get(id=self.object.book.id)
        book.available_copies +=1
        book.save()
        self.object.delete()
        return redirect('library:borrower-list')

library/templates/library/base.html
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>ACADEMLO's Library</title>
  </head>
  <style>


    .card-img-top {
    width: 100%;
    height: 15vw;
    object-fit: cover;
    }
    .card{
      margin: 1em auto;
    }
    .about__img {
    margin-top: 1em;
    justify-self: center;
    }
    .profile{
      margin: auto;
      text-align: center;
      font-family: 'Gill Sans', 'Gill Sans MT', 'Calibri', 'Trebuchet MS', sans-serif;
     
    }
    .about__img img {
    width: 200px;
    border-radius: .5rem;
    }
    label {
            padding-top: 10px !important;
            display: block;
        }
    th,td{
      text-align: center;
      margin: auto;
    }
    .flex-container{
      overflow: auto;
    }


  </style>
  <body class="container ">
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'library:home' %}">ACADEMLO's Library</a>
          <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'library:home' %}">Home</a>
              </li>


              
              
                {% if request.user.is_superuser or request.user.is_admin %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Members
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'library:member-list'%}">Member List</a></li>
                  <li><a class="dropdown-item" href="{% url 'library:member-create'%}">Add Member</a></li>
                 
                </ul>
              </li>
              {% endif %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Books
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'library:book-list' %}">Books List</a></li>
                  {% if request.user.is_superuser or request.user.is_admin %}
                  <li><a class="dropdown-item" href="{% url 'library:book-create' %}">Add New Book</a></li>
                  <li><a class="dropdown-item" href="{% url 'library:borrower-create' %}">Issue a Book</a></li>
                 {% endif %}
                 <li><a class="dropdown-item" href="{% url 'library:borrower-list' %}">Books Issued</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Account
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'library:member-detail' request.user.id%}">View Account</a></li>
                  <li><a class="dropdown-item" href="{%url 'library:logout'%}">Logout</a></li>
                  <li><a class="dropdown-item" href="{%url 'library:users-list'%}">All Users</a></li>
                  <li><a class="dropdown-item" href="{% url 'library:users-create'%}">Add User</a></li>
                </ul>
              </li>
              {% endif %}
            </ul>
            <form  method="GET" class="d-flex">
              <input class="form-control me-2" type="text" placeholder="Search" name="search-area" aria-label="Search" value="{{search_input}}">
              <button class="btn btn-outline-light" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
<div class="container" style="overflow: auto;">
{% block content %}  {% endblock content %}</div>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    
  </body>
</html>

library/templates/library/book.html
{% extends 'library/base.html' %}
{% block content %}
<div class="profile">
{% if book.pic %}
<div class="about__img img">
    <img src="{{book.pic.url}}" alt="">
</div>
{% else %}
<div class="about__img img">
    <img src="/static/avatar/open-book-clipart-03.png" alt="">
</div>
{% endif %}
{% if request.user.is_admin or request.user.is_superuser %}
<a  href="{% url 'library:book-update' book.id%}">Edit</a>
{% endif %}
<span><h1>{{book.title|title}}</h1></span>
<p style="width: 50%; margin: auto;">{{book.summary}}</p>
<p><h4 style="margin: auto;">Genre:</h4> {{book.genre.all|join:', '}}</p>
<p><h4 style="margin: auto;">Book Language:</h4> {{book.language}}</p>
<p><h4 style="margin: auto;">Pages:</h4> {{book.pages}}</p>
<p><h4 style="margin: auto;">ISBN:</h4> {{book.isbn}}</p>





</div>
{% endblock content %}

library/templates/library/book_form.html
{% extends 'library/base.html' %}
{% block content %}




<div class="card-body" >
    <a href="{% url 'library:book-list' %}">&#8592;Back</a>
    <form method="POST" enctype="multipart/form-data"action="">
    {%csrf_token%}
    <label >{{form.title.label}} </label>
    {{form.title}} 
    
    <label >{{form.author.label}} </label>
    {{form.author}} 
    <label >{{form.summary.label}} </label>
    {{form.summary}}
    
    <label >{{form.isbn.label}} </label>
    {{form.isbn}} 
    
    <label >{{form.genre.label}}</label>
    {{form.genre}} 
    
    <label >{{form.language.label}} </label> 
    {{form.language}}  
    
    <label >{{form.total_copies.label}}</label> 
    {{form.total_copies}}
    <label >{{form.available_copies.label}}</label> 
    {{form.available_copies}}
    <label >{{form.pages.label}}</label> 
    {{form.pages}}
    <label >{{form.pic.label}}</label> 
    {{form.pic}}

    <label> <input class="button" type="submit" value="Submit"></label>
    
    </form>
</div>



{% endblock content %}

library/templates/library/borrower.html
<h1>{{borrower}}</h1>

library/templates/library/borrower_confirm_delete.html
{% extends 'library/base.html' %}
{% block content %}


<div >
    <a href="{% url 'library:borrower-list' %}">&#8592;Back</a>
</div>

<div >
    <form method = "POSt">
        {%csrf_token%}
        <p>Are you sure you want to delete the book issued by'{{borrower|title}}'?</p>
        <input class="button" type="submit" value="Submit">
        </form>
</div>



{% endblock content %}

library/templates/library/borrower_form.html
{% extends 'library/base.html' %}
{% block content %}




<div  class="card-body">
    <a href="{% url 'library:borrower-list' %}">&#8592;Back</a>
    <form method="POST" action="">
    {%csrf_token%}
    <label >{{form.member.label}} </label>
    {{form.member}} 
    
    <label >{{form.book.label}} </label>
    {{form.book}} 
    <label >{{form.issue_date.label}} </label>
    {{form.issue_date}}
    
    <label >{{form.return_date.label}} </label>
    {{form.return_date}} 
    

    <label> <input class="button"  type="submit" value="Submit"></label>



    </form>
</div>


{% endblock content %}

library/templates/library/borrower_list.html
{% extends "library/base.html" %} {% block content %}


<table class="table" style="margin: auto;">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Member Name</th>
      <th scope="col">Book</th>
      <th scope="col">Return Date</th>
      <th scope="col">Fine</th>
      {% if request.user.is_admin or request.user.is_superuser %}
      <th scope="col">Action</th>{% endif %}
    </tr>
  </thead>
  {% if borrowers %}
  <tbody>
    {% for borrower in borrowers %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{borrower.member.name}}</td>
      <td>{{borrower.book.title}}</td>
      <td>{{borrower.return_date}}</td>
      <td>
      {% if borrower.fine <= 0 %}
      $ <span class="text-dark"> 
        {% else %} 
      $ <span class="text-danger">  
      {% endif %}
      {{borrower.fine}}
    </span>
  </td>
  
      <td>{% if request.user.is_admin or request.user.is_superuser %}
        <a href="{% url 'library:borrower-update' borrower.id%}">Update</a>  <a href="{% url 'library:borrower-delete' borrower.id%}">Delete</a>
        {% endif %}</td>
    </tr>

    {% endfor %}
  </tbody>
  {% else %}
  <tbody><tr><td colspan="6"> No Books Issued.</td></tr></tbody>
  {% endif %}
</table>

{% endblock %}

library/templates/library/information_form.html
{% extends 'library/base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<div class="profile">
<div >
    
    <a href="{% url 'library:login' %}">&#8592; Back</a>
</div>

<div >
    <h3>Fill in the form and the admins will register you and send the credentials in your email within 24 hours.</h3>
    <form method="POST" action="">
    {%csrf_token%}
    {{form|crispy}}
    <input class="button" type="submit" value="Submit">
    
    </form>
</div>

</div>

{% endblock content %}

library/templates/library/main.html
{% extends 'library/base.html' %} {% block content %}


<div class="row" style="margin: auto;">

{% for book in books %}

<div class="card" style="width: 18rem">
  <span style="text-align: center;"></span>
  {% if book.pic %}
  <img src="{{book.pic.url}}" class="card-img-top" alt="" />
  {% else %}
  <img src="/static/avatar/open-book-clipart-03.png" class="card-img-top" alt="">
  {% endif %}
  <div class="card-body">
    <h5 class="card-title">{{book.title}}</h5>
    <p class="card-text">{{book.summary}}</p>
    <a href="{% url 'library:book' book.id %}" class="btn btn-primary"
      >View Details</a
    >
  </div>
</div>


{% endfor %}


</div>

{% endblock content %}

library/templates/library/member_confirm_delete.html
{% extends 'library/base.html' %}
{% block content %}


<div >
    <a href="{% url 'library:member-list' %}">&#8592;Back</a>
</div>

<div >
    <form method = "POST">
        {%csrf_token%}
        <p>Are you sure you want to remove '{{member|title}}'?</p>
        <input class="button" type="submit" value="Submit">
        </form>
</div>



{% endblock content %}

library/templates/library/member_list.html
{% extends "library/base.html" %} {% block content %}
<table class="table"  style="margin: auto;">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Enrollment #</th>
      <th scope="col">Member Name</th>
      <th scope="col">Email</th>
      <th data-toggle="tooltip" data-placement="top" title="User types: [1:Member] [2:IT staff] [3:Librerian]"scope="col" hover-zoom>User Type</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  {% if members %}
  <tbody>
    {% for member in members %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{member.enrollment_no}}</td>
      <td>{{member.name}}</td>
      <td>{{member.email}}</td>
      <td data-toggle="tooltip" data-placement="top" title="User types: [1:Member] [2:IT staff] [3:Librerian]">{{member.user_type}}</td>
      <td><a href="{% url 'library:member-update' member.id%}">Update</a>  <a href="{% url 'library:member-delete' member.id%}">Delete</a>  <a href="{% url 'library:member-detail' member.id%}">Profile</a> </td>
    </tr>
    {% endfor %}
  </tbody>
  {% else %}
  <tbody><tr><td colspan="6"> No Members.</td></tr></tbody>
  {% endif %}
</table>
<p data-toggle="tooltip" data-placement="top" title="User types: [1:Member] [2:IT staff] [3:Librerian]">User type {{member.user_type}} (hover here)</p>
{% endblock %}

library/templates/library/register.html
{% extends 'library/base.html' %}
{% block content %}



<div class="card-body">
    <a href="{% url 'library:member-list' %}">&#8592;Back</a>
    <form method="POST" enctype="multipart/form-data" action="">
        {%csrf_token%}
        <label >
        {{form.user_type.label.all|join:', '}}
        <select name="select">
        <option value="value1">Member{{form.user_type.label.1}}</option>
        <option value="value2" selected>IT staff{{form.user_type.label.2}}</option>
        <option value="value3">Librerian{{form.user_type.label.3}}</option>
          </select>
        </label> 
        <label >{{form.email.label}} <span>(Add a valid email)</span></label>
        {{form.email}} 
        
        <label >{{form.name.label}} </label>
        {{form.name}} 
        
        <label >{{form.username.label}} </label>
        {{form.username}} 
        
        <label >{{form.enrollment_no.label}}</label>
        {{form.enrollment_no}} 
        
        <label >{{form.password1.label}} <span>(8 characters & alphanumeric)</span></label> 
        {{form.password1}}  
        
        <label >{{form.password2.label}}</label> 
        {{form.password2}}

        <label >{{form.pic.label}}</label> 
        {{form.pic}}

        <label >{{form.user_type.label}}</label>
        {{form.user_type}}



        

        <label> <input class="button" type="submit" value="Submit"></label>
        
        
        </form>
       
</div>




{% endblock content %}

library/templates/library/user.html
{% extends 'library/base.html' %}
{% block content %}
<div class="profile">
{% if user.pic %}
<div class="about__img img">
    <img src="{{user.pic.url}}" alt="">
</div>
{% else %}
<div class="about__img img">
    <img src="/static/avatar/images.png" alt="">
</div>
{% endif %}


<!-- <select name="select"> -->
    <!-- <option value="value1">Member</option> -->
    <!-- <option value="value2" selected>IT staff</option> -->
    <!-- <option value="value3">Librerian</option> -->
  <!-- </select> -->
 
<p><h1>{{user.name|title}} </h1></p>
<p data-toggle="tooltip" data-placement="top" title="User types: [1:Member] [2:IT staff] [3:Librerian]">User type {{member.user_type}} (hover here)</p>

<p>Enrollment No: {{user.enrollment_no}}</p>
<p>Date Joined: {{user.date_joined}}</p>


</div>

{% endblock content %}

library/templates/library/users_list.html
{% extends "library/base.html" %} {% block content %}
<table class="table"  style="margin: auto;">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Enrollment #</th>    
      <th scope="col">Member Name</th>
      <th scope="col">Email</th>
      <th data-toggle="tooltip" data-placement="top" title="User types: [1:Member] [2:IT staff] [3:Librerian]"scope="col" hover-zoom>User Type</th>
      <th scope="col">Profile</th>
    </tr>
  </thead>
  {% if users %}
  <tbody>
    {% for user in users %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{user.enrollment_no}}</td>
      <td>{{user.name}}</td>
      <td>{{user.email}}</td>
      <td data-toggle="tooltip" data-placement="top" title="User types: [1:Member] [2:IT staff] [3:Librerian]"> {{user.user_type}}</td>
      <td><a href="{% url 'library:users-detail' user.id %}">User profile</a></td>
    </tr>
    {% endfor %}
  </tbody>
  {% else %}
  <tbody><tr><td colspan="6"> No Users.</td></tr></tbody>
  {% endif %}
</table>
<p data-toggle="tooltip" data-placement="top" title="User types: [1:Member] [2:IT staff] [3:Librerian]">User: {{user}}, Type: {{user.user_type}} ↖🖱️(hover name)</p>
{% endblock %}